### ISSUE TITLE
OneDrive & Exchange restore of subfolder does not work unless full path to subfolder is specified

### ISSUE THREAD

**Issue by gmatev** [alcionai/corso#1146]
Consider a backup that has captured the following hierarchy:

```
/
   -> file1
   -> file2
   -> SubFolder/
       -> file3
       -> file4
       -> SubFolder2/
          -> file5
```

The following does not find any items:
```
corso restore --backup <backupId> --folder Subfolder2
```

The way to restore the items in the folder is:
```
corso restore --backup <backupId> --folder "SubFolder/Subfolder2"
```

It should not be required to specify the full path.

**Comment by ryanfkeepers** [comment]
@gmatev I'm looking at sorting out the nuances of folder matching at large, and wanted to clarifying expected behavior with you:

**Given:** a folder path in the hierarchy matching `/parent/child/`, where `/` is the root and `/parent/` is the first folder descending from the root, etc.

There are two methods of comparing an input to the folder path: `Prefix` and `Search`.

-----

Assumptions for `Prefix`, defined as: "the target matches any arbitrary prefix on the path string":

Matching examples:
* /
* /par
* /parent
* /parent/
* /parent/c
* /parent/child
* par
* parent
* parent/
* parent/c
* parent/child

Non-matching examples:
* /rent
* rent
* /child
* child
* ent/child/
* /ent
* /ent/child

These examples assume prefix comparison accepts any arbitrary string prefix.  If wanted, we could change the comparator to only succeed on complete path elements.  Eg: /parent would match, but /par would not.  

-----

Assumptions for `Search`, defined as: "any individual element in the path equals the target"

Matching examples:
* parent
* child

Non-matching examples:
* rent
* ent/chil
* parent/child

-----

Finally, on the topic of exposing the choice between these comparators to the user in the CLI: we've previously floated the idea of interpreting the input to characterize the difference.  IE: `--email-folders foobar` implies a single folder (foobar) and would default to a `Search` comparison.  Meanwhile `--email-folders foo/bar` implies a folder path (/foo/bar) and would use a `Prefix` comparison.

This approach is acceptable (if a little hidden) so long as we accept two points of ambiguity: 1/ we are unable to Search for single folders containing slashes (ex: a single folder named "foo/bar"). 2/ Single folder prefixing could be easily confused with searching ("inbox" vs "/inbox").  If we want to avoid ambiguity, we can separate flags to dictate each choice, like `--[search-]email-folders` or `--email-folders[-prefix]`.  

Let me know if those examples and suggestions match what you have in mind for this behavior, thanks!

**Comment by gmatev** [comment]
I think i follow the logic. 

I'm not a fan of the partial matches on filter. 

My preference would be:
* `--email-folders foo` - match any folder where `foo` is a path element. Does not matter if the folder is at the root, has a non-root parent, or has child folders. 
* `--email-folders foo/bar` - match any folder where complete path element `foo` is followed by complete path element `bar` 
* `--email-folders /foo/bar` - match complete path element `foo` (at the root) followed by complete path element `bar`
* Trailing `/` can be trimmed
* If someone names their folder itself `foo/bar` so be it. We won't find it

I think it is ok for no to forgo a partial path search. 

I don't think introducing separate switches is worth it at this stage.

**Comment by ryanfkeepers** [comment]
Okay, going to repeat this back to double check I understand everything.

> --email-folders foo - match any folder where foo is a path element. Does not matter if the folder is at the root, has a non-root parent, or has child folders.

Behavior defaults to `Search` comparison, where `--email-folders foo` will match any **complete folder name** in the path.  Therefore, all of the following will match the input:
* /foo/bar/baz/
* /baz/foo/bar/
* /bar/baz/foo/

> --email-folders /foo/bar - match complete path element foo (at the root) followed by complete path element bar

Any input where the initial character is `/` changes the behavior from Search to `Prefix` match, where `--email-folders /foo` will only match on:
* /foo/bar/baz/

Prefix match will upload complete path element matching, therefore **/foobar/baz/** would not match.

> --email-folders foo/bar - match any folder where complete path element foo is followed by complete path element bar

`Search` matching can specify any number of folders, so long as:
1. every element completely matches a folder name.  `a/b` matches `/a/b/c` but not `/aa/bb/cc/`
2. the folders are in sequence.  `a/b` matches `/a/b/c/` but not `/a/foo/b/`

**Comment by gmatev** [comment]
Spot on

**Comment by ashmrtn** [comment]
just catching up on this for PR review context

I think it may be possible to handle folder names with `/` in them if we do the following:
1. the user properly escapes embedded `/` in folder names as `\/` (ex. `foo\/bar` for a single folder and `foo\/bar/baz` for folders `["foo/bar", "baz]` together)
2. the CLI layer handles leading `/` semantics as in `/foo` denoting a prefix search (path package will not know what to do with this otherwise)
3. we run CLI input through the path package prior to matching

**Comment by ryanfkeepers** [comment]
Yup, I think we'll be able to manage all of that.

**Comment by ryanfkeepers** [comment]
@gmatev Noting input ambiguity, and the plan to handle i.

Given: `corso backup details exchange --email-folders foo,bar` the result set is 'any mail folder path containing either folder "foo" or "bar"'.

Given: `corso backup details exchange --email-folders /foo,/bar` the result set is 'any mail folder path prefixed by either "/foo" or "/bar"'.

Given: `corso backup details exchange --email-folders foo,/bar` the result set is both, "any mail folder path containing the folder "foo", or prefixed by "/bar"'.

**Comment by gmatev** [comment]
This looks right

**Comment by ryanfkeepers** [comment]
@gmatev #1224 is now merged with main.  A local test of a onedrive backup results as follows:

```sh
> corso.go backup details onedrive -json --backup ${bupid}
# plus some jq to isolate the folders in repoRef
[
  "files/drives/b!OHnIG-BSZ0GbJB7EQOfroNjykiltKpdMitTER8xRgGkGQXejH3FUS6m5hvjePHj0/root:/sibling",
  "files/drives/b!OHnIG-BSZ0GbJB7EQOfroNjykiltKpdMitTER8xRgGkGQXejH3FUS6m5hvjePHj0/root:",
  "files/drives/b!OHnIG-BSZ0GbJB7EQOfroNjykiltKpdMitTER8xRgGkGQXejH3FUS6m5hvjePHj0/root:/arquebus",
  "files/drives/b!OHnIG-BSZ0GbJB7EQOfroNjykiltKpdMitTER8xRgGkGQXejH3FUS6m5hvjePHj0/root:/arquebus/nestled"
]

# --folder /sibling,nestled
[
  "files/drives/b!OHnIG-BSZ0GbJB7EQOfroNjykiltKpdMitTER8xRgGkGQXejH3FUS6m5hvjePHj0/root:/sibling",
  "files/drives/b!OHnIG-BSZ0GbJB7EQOfroNjykiltKpdMitTER8xRgGkGQXejH3FUS6m5hvjePHj0/root:/arquebus/nestled"
]

# --folder /sibling
[
  "files/drives/b!OHnIG-BSZ0GbJB7EQOfroNjykiltKpdMitTER8xRgGkGQXejH3FUS6m5hvjePHj0/root:/sibling"
]

# --folder arquebus
[
  "files/drives/b!OHnIG-BSZ0GbJB7EQOfroNjykiltKpdMitTER8xRgGkGQXejH3FUS6m5hvjePHj0/root:/arquebus",
  "files/drives/b!OHnIG-BSZ0GbJB7EQOfroNjykiltKpdMitTER8xRgGkGQXejH3FUS6m5hvjePHj0/root:/arquebus/nestled"
]

```

I'll let you close the issue when you're satisfied with any additional testing you'd like done.

**Comment by vkamra** [comment]
Behavior looks correct
