### ISSUE TITLE
Emit `Repo Connect` event

### ISSUE THREAD

**Issue by gmatev** [alcionai/corso#1762]
Emit a `Repo Connect` event (same properties as Repo Init) but only when `corso repo connect XXXX` CLI command succeeds (this should not be done during the repository connections established for other CLI operations)

This will allow us to distinguish repo connect CLI command from other operations

**Comment by vkamra** [comment]
@neha-Gupta1 - take a look at this one. This would involve firing the [Repo Connect](https://github.com/alcionai/corso/blob/main/src/internal/events/events.go#L28) event when repo.Connect() is called from `connectS3Cmd`.

We could do this inside `repo.Connect()` but need to make sure this only happens when repo.Connect is invoked as part of the CLI command

**Comment by neha-Gupta1** [comment]
Merged in https://github.com/alcionai/corso/pull/2502
