### ISSUE TITLE
Split data.Collection along interface usage

### ISSUE THREAD

**Issue by ryanfkeepers** [alcionai/corso#1944]
## Issue
The `data.Collection` interface has two funcs that are used in both backup and restore, and three funcs that are only used in backup.  This forces many collection instances to comply with interface qualities that are meaningless to their situation.  This generates chaff and confusing implementation.

## Proposal
Split the interface into two parts:
```go
// Collection is the base info used in all cases.
type Collection interface {
	Items() <-chan Stream
	FullPath() path.Path
}

// BackupCollection is only required when backing up data.
type BackupCollection interface {
	Collection

	PreviousPath() path.Path
	State() CollectionState
	DoNotMergeItems() bool
}
```

**Comment by ashmrtn** [comment]
while we're doing this we may actually want to revisit the return type of `FullPath()`. Restores need an actual "resource path" that has all the fields populated and makes guarantees about that. Kopia needs only a `path.Builder` since it's just doing basic path manipulations and doesn't care about the structure of the path

This could also ease some of the discomfort we've had when making metadata paths etc since they've required all fields in the path
