### ISSUE TITLE
Add cli flag to toggle permissions restore

### ISSUE THREAD

**Issue by meain** [alcionai/corso#2028]
Follow up to https://github.com/alcionai/corso/issues/1774 . Add a flag `--preserve-permissions` or `--no-permissions` which can be used to decide if we should restore OneDrive permissions when restoring the data. This will be necessary as we might be restoring to a different user or under a different context. The default can probably be to not restore permissions.
The details are still to be finalized. /cc @gmatev

**Comment by gmatev** [comment]
@meain let's make this flag be `--restore-permission`. By default permissions will not be restored. Please also make sure it gets reflected in the docs and the examples for the restore onedrive command.

**Comment by meain** [comment]
Would `Options` or `ToggleFeatures` be a good place to pass this information onto the actual restore job? These currently seem to be just global flags though. Another option would be to add another `struct` specific to restore related operations.
https://github.com/alcionai/corso/blob/e35c6cd17eaaf0251f21271bba6e4d3089dd61bf/src/pkg/control/options.go#L7-L13

One important issue is that all the restore operations go through a single `Run` function irrespective of weather it is onedrive or exchange or any other.
/cc @ashmrtn @ryanfkeepers

**Comment by ashmrtn** [comment]
>all the restore operations go through a single Run function irrespective of weather it is onedrive or exchange or any other.

I'm not as worried about this at the moment. Eventually we may need to figure something out so it doesn't get too sprawled out, but for the moment I think it's alright for service/data categories that don't need the flag to just ignore it

**Comment by gmatev** [comment]
I do expect that we will have options at all levels that are specific to a service, operation, or both, so setting up the right pattern here makes sense to me. 

It may also be required for the proper handling of flags in our automated operations help and docs. If only at the global level, I expect this flag to show up everywhere which will be confusing.

**Comment by ryanfkeepers** [comment]
> Would Options or ToggleFeatures be a good place to pass this information onto the actual restore job?

@meain A flag in `Options` is sufficient here.  Let's not bloat out structure where it's not needed.

ToggleFeatures should only be used for feature toggling control, not for configuration.  It's a blurry line sometimes.  Best gut check is to ask "am I hiding this thing from production usage so that I can release it in a half developed state?".  If so, It's a Toggle.

> let's make this flag be --restore-permissions. By default permissions will not be restored

I wanted to double check on this.  1/ are we sure `permissions` is specific enough?  Would `restore-file-permissions` or `restore-item-permissions` be a better way to avoid confusion with other types of permissions in the future?  2/ if we're certain this is a boolean value, we can keep it.  But if we have reason to believe it won't be a boolean forever, to cut down on having multiple flags like `--[action-]permissions`, would it be better to have it receive arguments?  Ex: `--file-permissions restore`?

**Comment by meain** [comment]
> are we sure permissions is specific enough?

At least for OneDrive, I'm not aware of anything that might be confused with permissions. That said, I don't think `--restore-file-permissions` is a bad choice either.

> if we're certain this is a boolean value

Unless we want to something like restore permissions, but only for a certain user I thin it will remain a boolean. Not sure what you mean by `--action-permissions`. The permissions are used to specify who has read/write access to files/folders.

**Comment by gmatev** [comment]
> At least for OneDrive, I'm not aware of anything that might be confused with permissions. That said, I don't think --restore-file-permissions is a bad choice either.

The permissions refer to the permissions of the what is being restored. If I'm restoring a folder, this would be the permissions of the folder. I think `--restore-permissions` allows for both. 

I'm not sure I follow the other proposal around `--[action-]permissions`? Is this to be able to control something like whether we should backup permissions with `--permissions backup`? Currently don't anticipate not backing up as much as we can so probably wouldn't make sense to go that route.

**Comment by ryanfkeepers** [comment]
> I'm not sure I follow the other proposal around `--[action-]permissions`?

Basically: are we concerned about a future with N different `--[action-]permissions` when we could instead have a single `--permissions action`?  For example, see: https://github.com/alcionai/corso/issues/2185.  The latter would set us up for easy extensibility.

Mostly trying to push the check up front as much as possible, so that we minimize tickets like 2185.
