### ISSUE TITLE
Do not add `.meta` files to backup details

### ISSUE THREAD

**Issue by meain** [alcionai/corso#2498]
As of now, the details file for OneDrive contains both `.data` and `.meta` files, but it is not necessary to store that information in details file. We should be able to figure out that the backup contains `.meta` files by looking at the backup version and augmenting the list in [formatDetailsForRestore](https://github.com/alcionai/corso/blob/43e5ccdb5bf03add030304510eb25a4559961d65/src/internal/operations/restore.go#L342). We can do this by dropping the need for info for metadata.

Prev discussion: https://github.com/alcionai/corso/pull/2473#issuecomment-1428398365

**Comment by ashmrtn** [comment]
as of right now, we only need to fetch dir meta entries (I've merged a PR to fetch file metadata inline already). I've been working on another patch to fetch dir meta entries inline as well, but got caught up with some other OneDrive changes for delta token-based incrementals. Once the dir meta patch goes in though we won't need to add anything to the list of items from backup details. We'll just need to switch to using a struct that doesn't implement the [StreamInfo](https://github.com/alcionai/corso/blob/b646f502eff2f762c6ddec3e38e08634e14176f6/src/internal/data/data_collection.go#L107) interface as that's what [kopia wrapper](https://github.com/alcionai/corso/blob/b646f502eff2f762c6ddec3e38e08634e14176f6/src/internal/kopia/upload.go#L345) uses

I think the only remaining question will be how to handle these items during details merging. I currently have it setup to [return an error](https://github.com/alcionai/corso/blob/b646f502eff2f762c6ddec3e38e08634e14176f6/src/internal/operations/backup.go#L609) if items were not found, just so we know if something odd is happening. However, these are expected to not be found

**Comment by ashmrtn** [comment]
I was thinking about this the other day and we may want to wait a bit before wrapping this up now that #2606 is in. If we remove these entries I'm not sure if details merging during incremental backups will succeed because it will think we should have found more entries than we did. I haven't tested this to see if that's what will actually happen, but it seems possible that it will since the base snapshot doesn't know what items do and don't have details entries associated with them (kopia [code](https://github.com/alcionai/corso/blob/13a8c72f2853b79efdecd9580ebae36346c222d7/src/internal/kopia/upload.go#L170) that generates entries to merge). Being able to put this off assumes that both the `.meta` and `.dirmeta` entries are ignored

Once we figure out a way to handle items that may not have backup details entries (or we're alright with [relaxing the restrictions](https://github.com/alcionai/corso/blob/13a8c72f2853b79efdecd9580ebae36346c222d7/src/internal/operations/backup.go#L604) in merging entries) we can move forward with this

**Comment by ashmrtn** [comment]
actually, since we're using the `Items()` call when merging details I guess we should deal with this sooner rather than later as it's currently causing failures for incrementals
