### ISSUE TITLE
Automate running sanity checks via CI

### ISSUE THREAD

**Issue by meain** [alcionai/corso#2535]
As of now, we only run very minimal checks against the artifacts generated in the CI and manually running sanity check (backup -> restore -> incremental backup -> restore) against all architectures and platforms is not feasible. The idea is to automate this via GitHub CI. This can be a manually triggered job(by specifying a commit or against main) which will be run before we do a release and can be used to make sure everything is working.

**Comment by neha-Gupta1** [comment]
This test has following steps:-

1. Download and install Corso using instructions in Docs
    Expectation: Corso is installed and `corso --version` returns as expected
    
2. Create a new repo
    Expectation: New repo is successfully created
    
3. Create first backup for a single user
    - Exchange
    - OneDrive
    
    Expectation: Each backup is successful and available with `corso backup details <service>`
    
4. Create another backup without any changes to the user account data (test incremental)
    - Exchange
    - OneDrive
    
    Expectation: Backup should complete faster and output should indicate that no new items were added to backup
    
5. Restore data for user from full backup. For all cases restore an item and a folder for each type
    - Exchange - mail, events, contacts
    - OneDrive - files
    
    Expectation: Each restore is successful and can be seen in user’s M365 account
    
6. Create backup again after restore (test incremental)
    
    Expectation: This should pick up newly restored files form (5) 
    
7. Restore items from the newly picked up previously restored folders in (6)

**Comment by neha-Gupta1** [comment]
**Implementation in** - https://github.com/alcionai/corso/pull/2622 

- version command
- Repo init and connect
- backup and restore of exchange and Onedrive
- verify correct no. of emails restored
- verify file sizes restored and roles on folder are correct.
- incremental backup and verification of the same

**Further enhancement-**

- check actual email data instead of just no. of emails
- verify contacts and calendar
- permission in Onedrive
- slack notification on failure
- if we receive an email in between a backup and restore, we will fail the test as the counts won't match

**issues for handling enhancement-**

https://github.com/alcionai/corso/issues/2743
https://github.com/alcionai/corso/issues/2742

**Comment by neha-Gupta1** [comment]
Closing this issue. Enhancement will be tracked in - https://github.com/alcionai/corso/issues/2742
