### ISSUE TITLE
CLI: SharePoint: LibrariesSelector Expansion

### ISSUE THREAD

**Issue by dadams39** [alcionai/corso#2602]
Expand `SharePoint.Libraries` from data  selector to the following:
- [ ] SharePoint.Libraries --> library --> the name of the document library within the site
- [ ] `SharePoint.Libraries.library` --> library-Folder --> the name of the folder within the document library
- [ ] `SharePoint.Libraries.library.folder` --> library-item --> name of the item within the folder

- Restore should be able to restore to all three levels of granularity.

**Comment by gmatev** [comment]
@dadams39 Let's tweak the above a bit. For Document Libraries I think we can adopt terminology and selectors consistent with OneDrive for `details` and `restore`
- `folder` - refers to the path within to a particular folder
  * This includes both the library as well as any sub-folder - e.g. `Documents` refers to the root of the `Documents` document library, while `Documents\FolderA` refers to FolderA within a document library. 
  * `folder` is optional when `--file` is used by ID since the file selector is sufficient
 
- `file` - refers to the name of a file. can use either a file name or an ID (same as Onedrive)

Additional selectors (same semantics as OneDrive)
- `--file-created-after`
- `--file-created-before`
- `--file-modified-after`
- `--file-modified-before`

**Comment by dadams39** [comment]
Closing with the completion of #2679.
