### ISSUE TITLE
Support specifying User ID instead of User UPN for backup operations

### ISSUE THREAD

**Issue by vkamra** [alcionai/corso#2825]
User UPNs can change (rename) and supporting User IDs will allow working around that.

Even if we do not expose this in the CLI - it would make sense to start resolving to User IDs internally and use those instead of UPNs. This future proofs if the user is renamed and will allow incremental backup chains to be maintained.

**Comment by ryanfkeepers** [comment]
## Assumptions
* All storage will utilize the ID.
* All end-user display (eg, CLI) will prefer the owner display name.
* In cases where no display name exists (or is sensible), the ID will be used for both values.
* CLI and SDK interfaces can accept either display names, interchangeably.

## Proposal
Ensure we store two values in the operation.Backup and backup.Backup structs:
* ResourceOwner string (the ID)
* ResourceOwnerName string (the display name)

ResourceOwner already exists, and is taken from the selectors.DiscreteOwner value.  Ownership of display names doesn't align with the design of selectors; we're better off passing the display name value into the operation, and letting that struct maintain ownership.

## Challenges/Gotchas
### order of operations
Currently, the resource owner isn't validated until a backup is underway, when we construct a GC client.  If we want ids and names to be handled interchangeably, we'll need to move the gc client construction up earlier into the operation creation (instead of run) to gather both values early.

### listing backups
Suppose a user creates backup B1 for an owner with name N1.  The user then changes their name to N2.  Another backup creates B2.  B1 and B2 will list as having different owners.

### utilizing prior display names
No current issues, but a potential future gotcha.  If a situation arises where a user attempts to perform an action involving an out-of-date display name (ex: listing backups filtered by owner name), and we attempt to resolve that display name to the user ID beforehand, validation could fail due to the old owner name not appearing in the results.

### collisions over time
(note: Investigation pending.)  Is it possible for owner A to switch their name from N1 to N2, and then owner B switch their name from N3 to N1?  If so, what happens to corso lookups as a result?

### testing
Integration testing of owner name changes is implausible, since a stable test would need to avoid race conditions with other tests acting upon the same external resource.  Mocks are our best option for controlled testing.

## Owner ID in Storage Paths
Currently, all exchange and oneDrive data is stored using the user's PN (ie, their display name) as the ID.  To complete this change, we'll want to begin storing all files under the user's ID instead of their PN.  When we introduce this change, one of the following will be true.  Corso will need to...
* run a controlled migration across backup versions to re-path all existing data without loss (high work, low customer impact, high impact from hidden bugs).
* force a non-incremental backup to re-path all existing data, thus deleting all currently stored data (moderate work, moderate customer impact, minimal impact from hidden bugs).
* do nothing, allowing all prior data to merge into the new backup, thus duplicating all currently stored data.  Tombstones may clean up some of the old values (low work, moderate customer impact, low impact from hidden bugs).

**Comment by gmatev** [comment]
@ryanfkeepers  Overall, this seems more complicated than it needs to be. Maybe we can start more incrementally with a simpler version that attempts to reduce everything to using the stable ID internally as quickly as possible and dropping the requirement for interchangeable use and the complexity associated with handling changes over time. Roughly the following:
* Introduce an API only mechanism to specify resource by ID (the stable ID for that). CLI can stay friendly ID (e.g. email, site URL that can mutate) focused
* Using them interchangeably seems to increase complexity and can be dropped - separate mechanism in the SDK for stable ID. 
* Resolving the friendly ID to stable ID at some early point in the workflow seems like a good idea
* All lookups for details, filtering etc happen on the stable ID even if they were initiated with the friendly ID. If the friendly ID does not resolve properly an error can be returned

**Comment by ryanfkeepers** [comment]
@gmatev Ah, thanks for the response.  I realize I omitted some details that allowed assumptions of complexity to creep through.  Short response: your suggests are already what I had in mind.

Longer response: we already have most of this pattern implemented for sharepoint juggling between webURLs and site IDs.  "interchangability" only extends to the surface level interfaces, primarily the CLI, where we want users to use friendlier identifiers.  Everything beyond that point makes a quick swap to the stable IDs under the hood.  There's no plan to allow for interchange beyond the top most interface.

**Comment by ashmrtn** [comment]
>ResourceOwner already exists, and is taken from the selectors.DiscreteOwner value. Ownership of display names doesn't align with the design of selectors; we're better off passing the display name value into the operation, and letting that struct maintain ownership.

This makes me a little nervous, as I'd much prefer some sort of interface we can use to hide where display name/ID is being sourced from. I think it may also make some data passing easier and allow for refactoring down the road

For instance, if we switch to using IDs in GC and KW, how is the progress bar stuff going to work? Are we going to have to start threading information about the display name through the whole stack to accomplish that? If we are, it seems like it would be better to assume we have "something that has the display information" which may or may not also allow for filtering/selecting resources. That can be represented with an interface which, right now, would have a concrete implementation that contains a selector (for the ID) and the display name. If, down the road we refactor and bring display names into selectors somehow the interface and code using it need not change

**Comment by vkamra** [comment]
@ryanfkeepers - let's also figure out whether we do this only for new repositories? It will add some extra code that we carry forward though (to maintain backwards compatibility) but will mean we don't break incremental chains and force a full backup for existing repos when this change is introduced

**Comment by ashmrtn** [comment]
>I still maintain that the selector is the wrong owner

I'm not saying selector has to be the owner for this data. I'm saying if we make something like

```go
type Namer interface {
  DisplayName() string
  ID() string
}
```

Then we could make a concrete implementation like

```go
type namerV1 struct {
  displayName string
  sel selectors.Selector
}

func (n namerV1) DisplayName() string {
  return n.displayName
}

func (n namerV1) ID() string {
  return n.sel.ResourceOwner
}
```

That hides the fact that the selector is generating the ID while still ensuring we're returning consistent data between `ID()` and `selector.ResourceOwner` as it's both sourced from the selector. The `Namer` interface can then be passed around and used as needed. If we decide to change things down the road we're free to do so because exactly how we're getting the human-readable name and the ID is abstracted due to the interface

**Comment by ryanfkeepers** [comment]
> only for new repositories

Sounds like a way to shard our storage structure.  I fear the maintenance of multiple storage designs would be much larger over time, more prone to gotchas, and require much more cognitive load, than the work to migrate them across the change.  

>  I'm saying if we make something like

I grok the proposal, though thank you for the extra detail.  Bit of a soapbox: Interfaces that only supply data and do not contain dependency injection create abstraction for its own sake.  A centralized transformation followed by passing concrete data makes code cleaner and minimizes mental model.  What we require in this case is data, not behavior.
