### ISSUE TITLE
Is "Sites.Selected" Permission Supported?

### ISSUE THREAD

**Issue by aldycool** [alcionai/corso#3927]
Hi,

I've read the docs for the Azure AD Application permissions, and it turns out that it needs "Sites.FullControl.All". Is this really necessary? we have restrictions in our company to not allow 3rd party apps to access 100% of our sites. Is the "Sites.Selected" permission can be supported? Thanks.

**Comment by ryanfkeepers** [comment]
Hello @aldycool!  Thanks for the question.  The `Sites.FullControl.All` permission is suggested because it provides the shortest path to complete backup and restore access.  We haven't thoroughly tested `Sites.Selected` at this time, and so I can't say with total assurance that it'll work as expected.

In our manual testing we have successfully completed backups with only that permission.  Restore testing is still underway.  And, of course, certain functionality like backing up all sites with the flag `--site '*'` isn't adapted to selective permissions.

Overall, I say that if you've been able to test successfully with the `Sites.Selected` permission, both for restores and backups, then you shouldn't have anything to worry about!

If you have further questions, I recommend joining the [Corso Discord](https://discord.gg/JpwCbYdC)!  We'd be happy to hear back about whether or not the change in permissions worked for you.

**Comment by vkamra** [comment]
Closing this as answered. @aldycool - let us know if you have any other follow up questions!
