### ISSUE TITLE
Allow kopia config file path overrides

### ISSUE THREAD

**Issue by pandeyabs** [alcionai/corso#4443]
### What happened?

Currently we place the [kopia config file](https://github.com/kopia/kopia/blob/45c1f0950f5fd983b38b9282f08a5d52f4cdfefe/site/content/docs/Reference/Command-Line/_index.md?plain=1#L68) at `/tmp/repository.config`. This file maintains repo connection params. This file is shared between all corso instances which might be running in parallel on the system, unless user is running the instances in separate containers.

This shared file model can be a cause of bugs. For e.g. consider a case where a user is doing multiple concurrent backups to different repositories. The kopia config file will only reflect the last written repo details. 

We've also seen reports from users where corso instances error out simultaneously writing to the config file. 
`connecting to repo: unable to write config file: error writing file: cannot replace "/tmp/repository.config" with tempfile "/tmp/repository.config2296101656": rename /tmp/repository.config2296101656 /tmp/repository.config: operation not permitted`

**Proposal:**
1. Allow corso cli users to override path via a `--kopia-config-file` flag or similar, or an environment var. 
2. Change the default location of the config file. Make it per $USER. Just like the corso config file. 

### Corso Version?

Corso v0.13.0

### Where are you running Corso?

NA

**Comment by vkamra** [comment]
>Change the default location of the config file. Make it per $USER. Just like the corso config file.

Using the corso config file location would unify this configuration and also allow the user to override.

**Comment by ashmrtn** [comment]
after some discussion:
* we should persist the kopia config file at the same parent location as the corso config file
* we need per-corso instances of the kopia config file and kopia cache location
* for now we can continue to locate the kopia cache at the same place as the corso config file/kopia config file
* in the long run we may consider allowing the kopia cache location to be configured separately. This would better match general Linux behavior of allowing config files to live in a "well-known" location ([XDG spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)) while also not blowing up the location with lots of data from the kopia cache

**Comment by meain** [comment]
>     * we should persist the kopia config file at the same parent location as the corso config file
Hmm, I see two problems with this:

- What is the corso config is on a read-only directory or provided using shell directives like `<()` which might not have a writable parent dir associated with it.
- What if the user has multiple corso config files in the same dir. This seems to the pattern that I have seen mostly on Discord.

> 
>     * we need per-corso instances of the kopia config file and kopia cache location
> 
One per instance seems excessive. Should we be concerned about the cleanup of the kopia config and cache, primarily the cache.

**Comment by vkamra** [comment]
It seems like for this use case that's not very common - allowing users to specify a location where their config lives (a --config-dir override?) would satisfy the requirement of being able to run multiple corso instances on a machine (against different repos) concurrently. Does that work?

**Comment by meain** [comment]
I guess it could. Are you suggesting that we use that instead of `--config-file` and have a predefined filename for the corso config within the directory?

I have another possible option, but not sure if it is overengineering a bit. What if we create a dir in ` /tmp` or `.cache` for that matter the kopia config but inside a folder which will be a cache of the corso config file, ie `/{tmp,.config}/corso/kopia-<hash of current corso config>/repository.config`.

**Comment by meain** [comment]
Looking at Discord, I got the feeling that people will have a single directory with all the corso configs, but if you don't think that would be case, I guess we can probably avoid worrying about it for now.

**Comment by HiteshRepo** [comment]
> uggesting that we use that instead of `--config-file` and have a predefined filename for the

I was thinking on the same lines, to have a function that gives out a hash based on corso config and create kopia config file by appending the hash within same directory as corso config.

**Comment by HiteshRepo** [comment]
With latest release [v0.16.0](https://github.com/alcionai/corso/releases/tag/v0.16.0), this issue is resolved. Thereby allows to run concurrent backups for different accounts (provider/storage/both). 

What has changed broadly:
1. The location of the repository config file.
2. The naming convention of repository config file.

Here are various scenarios:
1. If environment variable **CORSO_CONFIG_DIR** is set to ‘**/test/directory**’ and flag **--config-file** not provided while ‘**corso repo init..**’ or ‘**corso repo connect..**’
    1. **.corso.toml** should be created at **/test/directory**
    2. **repository-<account-config-hash>-<storage-config-hash>.config** should be created at **/test/directory**
2. If environment variable **CORSO_CONFIG_DIR** is not set and flag **--config-file** is provided as **/test/directory-2** while ‘**corso repo init..**’ or ‘**corso repo connect..**’
    1. **.corso.toml** should be created at **/test/directory-2**
    2. **repository-<account-config-hash>-<storage-config-hash>.config** should be created at **/test/directory-2**
3.. If environment variable **CORSO_CONFIG_DIR** is not set and flag **--config-file** is also not provided while ‘**corso repo init..**’ or ‘**corso repo connect..**’
    1. **.corso.toml** should be created at **/home/<user>**
    2. **repository-<account-config-hash>-<storage-config-hash>.config** config should be created at **/home/user**
4. For same account and same storage provider configs, repo config file name will be same.
5. For same account and different storage provider configs, repo config file name created will be different. 
6. For different account and same storage provider configs, repo config file name created will be different.
