### ISSUE TITLE
Backup Verification

### ISSUE THREAD

**Issue by aldycool** [alcionai/corso#5293]
Hi,

Is Corso able to do some backup verification? Means that whatever being backup, its integrity is intact and will be able to be restored later?

This is just a general question but it is commonly asked in backup solutions. Maybe we already have thoughts about doing this with Corso. Thanks.

**Comment by meain** [comment]
Hey @aldycool , we unfortunately don't have any provision as of now to just check the integrity of the backup.

That said, one suggestion would be to export the data out of corso. You can find the documentation in the [export section](https://corsobackup.io/docs/cli/corso-export-onedrive/) of each service. This will provide guarantees about being able to read and process the data within the backup. _Also, since exports write out the data to the fs, you can run additional checks on the exported content if necessary._

**Comment by aldycool** [comment]
Hi @meain , alright, thank you for your explanation. I'll look into the export functions. Thanks.
